backend = "glx";
vsync = true;

corner-radius = 12
rounded-corners-exclude = [
  "class_g = 'polybar'"
];

blur-method = "dual_kawase";
blur-strength = 8;
blur-background = true;
blur-background-fixed = true;

inactive-opacity = 0.9;
active-opacity = 1;
frame-opacity = 0.9;

opacity-rule = [
   "95:class_g = 'kitty'", 
   "100:class_g = 'Brave-browser'"
];

shadow = true;
shadow-radius = 12;
shadow-opacity = 0.9;

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 4;
